name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        Xvfb :99 &
        export DISPLAY=:99

    - name: Compile
      run: javac -d . src/LoginApp.java test/LoginAppST.java

    - name: Run Tests
      run: xvfb-run java LoginAppST
      env:
        DISPLAY: :99
