name: CI/CD Pipeline

on:
  pull_request:
    branches: [ "main", "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Compile code
      run: |
        mkdir -p target
        javac -d target -cp "lib/*:." src/LoginApp.java test/LoginAppST.java
    - name: Run tests
      run: |
        java -cp "target:lib/*" test.LoginAppST
    - name: Merge to main/master
      if: success()
      run: |
        git push origin HEAD:main
